### ISSUE TITLE
Bug reading channel names with ! in name

### ISSUE THREAD

**Issue by rui-castro** [XMLTV/xmltv#10]
[Configure.pm](https://github.com/rui-castro/xmltv/blob/master/lib/Configure.pm#L87) can't handle channels with an "!" in the name.

This bug was already reported in https://sourceforge.net/p/xmltv/bugs/521/

**Comment by honir** [comment]
Hi,
Thanks for your contribution. I'm not quite sure what your regex is trying to achieve - the lines in the config file are of the format

`channel=xxxx`  or `channel!xxxx`

There's no need to check for ! within the $key 

A simpler fix might be to just make the first group ungreedy 

`         my( $key, $sign, $value ) = ($line=~ /^(\S+?)([=!])(.*?)\s*(#.*)?$/ );`

which allows for channels to contain !  such as

`channel=E!`


(Note: SF#521 wasn't because it "contained" a ! but because it _ended_ with ! )

**Comment by rui-castro** [comment]
@honir regex `^([^\r\n\t\f\v =!]+)([=!])(.*?)\s*(#.*)?$` matches keys that don't have any white space ('\r', '\n', '\t', '\f', '\v', ' '), "=" or "!". It works, but your solution is simpler ;)

If your solution is included in the next release it would be great.

**Comment by rui-castro** [comment]
@honir I've update my PR #11 with your solution.

**Comment by knowledgejunkie** [comment]
Thanks for updating PR #11 

However, it would be much better if grabbers followed the recommended use of RFC 2838 identifiers for channels, and then this issue becomes moot

**Comment by honir** [comment]
True. But RFC 2838 is overly restrictive in as much as it doesn't permit the coding of broadcaster's genuine channel names such as E! and 5* and thus forces a scheme where these have to be arbitrarily translated to an unregulated alpha name (since it doesn't allow underscore in the name which might be the normal translation for invalid chars).

**Comment by knowledgejunkie** [comment]
It's arbitrary if the channel identifier conversion is processed automatically from the channel's "real name".

If it's actually managed, which I guess underpins the spirit of RFC 2838, then as with DNS itself it's never a problem (E! -> eonline.com, 5* -> 5star.channel5.com).

**Comment by honir** [comment]
Resolved
