### ISSUE TITLE
tv_imdb

### ISSUE THREAD

**Issue by Chris230291** [XMLTV/xmltv#123]
I have been looking at the tv_imdb filter and was wondering if it can modify an existing xml file and replace all titles with the original title and perhaps the description too?

I tried to set it up and have a play but it seems to be broken? The `--prepStage all --download` step fails because of bad links I think. After a quick google I appear to have found the links here https://datasets.imdbws.com/

Can anyone help?

Thanks,
Chris

**Comment by knowledgejunkie** [comment]
Please also refer to #17

**Comment by Chris230291** [comment]
Thanks for the reply.
So it has not been updated to support the new format yet?

Assuming it was working, would it do what I want?

**Comment by knowledgejunkie** [comment]
According to the manpage and the code in lib/IMDB.pm, tv_imdb will replace the title with that found in the IMDB data if a match can be made, and will also replace the description field if the --with-plot option is specified when running tv_imdb.

tv_imdb has not been updated for a _long_ time but if Amazon are making up-to-date information available again for non-commercial use this will likely trigger more development (and/or patches!)

**Comment by Chris230291** [comment]
OK. The data at https://datasets.imdbws.com/ is up to date. That topic you linked seems to suggest that the data has not been updated since 2017, and wont be anymore, but that is incorrect.

**Comment by honir** [comment]
There are two (official) data sources for IMDb data: 1) the ftp files we have been using for the past 23 years, 2) the new TSV files.

The FTP files in (1) have not been updated since Dec. 2017, and Amazon have said they will _not_ be updated anymore.

The TSV files in (2) are updated daily but these files are very different in content to (1), with much data no longer available.

Notably they contain only the top 3 genres and top 3 actors, and do _not_ contain any film descriptions. 

Compare https://www.imdb.com/interfaces/ with ftp://ftp.fu-berlin.de/pub/misc/movies/database/frozendata/ and you will see how minimalist the 'new' files are.

**Comment by honir** [comment]
The usual reason the tv_imdb building of local database fails is because of Perl running out of memory. Your best bet is to download the files manually and then run each stage one at a time, to avoid Perl memory errors.

**Comment by honir** [comment]
tv_imdb has been changed  [(1)](https://github.com/XMLTV/xmltv/blob/master/filter/tv_imdb)  [(2)](https://github.com/XMLTV/xmltv/blob/master/lib/IMDB.pm) and now uses significantly less memory. The download links used by the program are correct. So you should have no problem building your local database now.

Your initial question was answered above.
