### ISSUE TITLE
Augment Rules for Series / Episode in sub-title

### ISSUE THREAD

**Issue by philled** [XMLTV/xmltv#127]
XMLTV Version?
--------------
0.6.1-1

XMLTV Component?
----------------
tv_augment

What did you expect to happen?
------------------------------
Is it possible to use any of the tv_augment rules to clean up XMLTV data that has "Series x Episode y" data like this in the sub-title and move it to episode-num rather than sub-title?

```
  <programme start="20210102002000 +1100" stop="20210102005100 +1100" channel="abccomedy.free.au">
    <title lang="en">The Thick of It</title>
    <sub-title lang="en">Series 4, Episode 8</sub-title>
    <desc lang="en">The final reckoning. Every dog has its day, but as the fallout from the inquiry takes its toll, the everyday problems of government continue unabated.</desc>
    <credits>
      <actor>Chris Langham</actor>
      <actor>Peter Capaldi</actor>
    </credits>
    <category lang="en">Comedy</category>
    <category lang="en">Comedies</category>
    <episode-num system="xmltv_ns">3 . 7 . </episode-num>
    <subtitles type="teletext" />
    <rating>
      <value>MA</value>
    </rating>
  </programme>
```

Did you see any warnings/errors?
--------------------------------
Negative repeat count does nothing at /usr/share/perl5/XMLTV/Augment.pm line 3319.

What other software are you using?
----------------------------------
**Operating System:**
"Ubuntu 20.04.1 LTS

**Perl Version:**
5.30.0-9

**Comment by honir** [comment]
You can use the _extract_numbering_from_episode_ rule which as the sample configuration file says:
`Rule A5.2 - Extract series/episode numbering found in <sub-title>.`

You may also want to set  _update_existing_numbering_  if you want to overwrite any existing "episode-num".

But note that won't make any difference in the example you give, since episode-num "3 . 7 . " is the correct representation of "Series 4, Episode 8"  
(see: [link](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd) to DTD)
