### ISSUE TITLE
Remove CVS $Id tags from grabbers/utilities

### ISSUE THREAD

**Issue by knowledgejunkie** [XMLTV/xmltv#16]
These orphaned tags are leftover from the migration to git, and need to be tidied up before we release 0.5.71 (or 0.6.0).

Many grabbers and utilities used the "CVS $Id" tags when generating their $VERSION string.

These need to be removed before the next release and the version string generated differently so that $grabber --version and grabber validation continue to work.

Core utilities should probably be tied to the version of XMLTV.pm. Grabbers could be handled similarly, but could also be versioned manually or use some git magic.

**Comment by garybuhrmaster** [comment]
Adding to the discussion....

FWIW, I do not consider the tags completely orphaned.  In my upstream grabber I have been (independently) maintaining CVS compatible $Id ... tags to feed into ParseOptions (since ParseOptions requres it) since the beginning, and have been manually updating them for commits (usually, I occasionally have to have another commit to update the values).  Those numbers/dates are, of course, different than what CVS uses for its autogenerated tags.

As far as git magic, as I recall (I am not a git expert, so maybe there is some better magic available), getting meaningful file versioning info is a bit problematic in git since this is just one large repo (changing to submodules/subpackages/subtrees is likely a complexity that far far far exceeds the value).  When building packages, I suppose one could consider using something like "git rev-list --count <commit> <file>" and "git log -1 --format=%cd <file>" to get the total number of commits and the last commit date on a grabber to auto create a version that is sort of like the current CVS $Id tag info (I have not considered the details, just thinking about what git commands are available to collect similar info to the CVS $Id tag), but that will only work with whatever build scripts you have (and may not be considered by all as a general solution).

Since I am already doing it, I think that having grabbers manually versioned is not a bad solution, but I do understand that adds an additional step for authors.  Some of this was, of course, discussed many months ago on the -devel list.

What might make the transitions easier if you intend to let/encourage authors to make the various changes over time is to change ParseOptions and (XMLTV::Version?) to make version specification optional (rather than required) so that if it is not provided one generates the XMLTV core value (that makes it easy for authors to take a default if they choose to do so).  And adding a revised version standard (the regex no longer looking for $Id ... but some new version style string), perhaps as versionTNG? for those that want to provide more info might be a way forward.

**Comment by jnylen** [comment]
Hi,
I guess CVSID is similar to the commit id?

In that case, in travis you have the environment variable: `TRAVIS_COMMIT`, which if I recall correctly should respond with the commit that is currently running.

Otherwise `git rev-parse origin/master` should return the sha hash for origin/master.

**Comment by stefanb2** [comment]
Please remember that git magic won't work when building from release tarball. So the source tree needs to include at least one manually updated version source, e.g. VERSION file.

For builds from git tree I would suggest to use output from `git describe`, e.g. `v0.5.70-127-gd1f86c0d`, unless git HEAD should happen to be a version tag, i.e. the output would be `v0.5.70`. Showing the git commit determines the version of all source files that went into the build, i.e. you won't need another version number for grabbers in that case.

For a build from a release tarball the tag would determine which source files went into the build. So in practice you wouldn't need another version number for grabbers either.

**Comment by jole7** [comment]
building on linux,
```
git log | head
	commit 328199b01e73960e17cda62ba6dcfdb4a07f4a11
	Author: Geoff <honir999@gmail.com>
	Date:   Mon Jan 7 12:22:19 2019 +0000

	    Disable broken grabbers (SF#517) (#45)

	commit 9c809d44e865eb736ec9cc85bbea20c976e61353
	Author: Geoff <honir999@gmail.com>
	Date:   Mon Dec 31 19:00:00 2018 +0000
```

installed
```
ls -al `which tv_grab_zz_sdjson`
	-r-xr-xr-x 1 root root 37K Jan 12 08:55 /opt/xmltv/bin/tv_grab_zz_sdjson*
```

execs with error,
```
tv_grab_zz_sdjson --version
	Name "Params::Validate::NO_VALIDATION" used only once: possible typo at /opt/xmltv/bin/tv_grab_zz_sdjson line 238.
	XMLTV module version 0.5.70
	Invalid version $Id$ at /opt/xmltv/bin/tv_grab_zz_sdjson line 129.
```

checking
```
/opt/xmltv/bin/tv_grab_zz_sdjson
		#!/usr/bin/perl -w
		
3		my $grabber_cvs_id = '$Id$';
		...
129		my ($opt, $conf) = ParseOptions({
		    grabber_name => $grabber_name,
		    version => $grabber_cvs_id,
		...
```

I understand there's no 'next release' yet.  But is it currently fixed in git src?

It's unclear from reading above -- where/how does "Id" need to be set for the entire build-from-git-not-cvs to be 'happy'?

**Comment by knowledgejunkie** [comment]
> building on linux,
> 
> ```
> git log | head
> 	commit 328199b01e73960e17cda62ba6dcfdb4a07f4a11
> 	Author: Geoff <honir999@gmail.com>
> 	Date:   Mon Jan 7 12:22:19 2019 +0000
> 
> 	    Disable broken grabbers (SF#517) (#45)
> 
> 	commit 9c809d44e865eb736ec9cc85bbea20c976e61353
> 	Author: Geoff <honir999@gmail.com>
> 	Date:   Mon Dec 31 19:00:00 2018 +0000
> ```
> 
> installed
> 
> ```
> ls -al `which tv_grab_zz_sdjson`
> 	-r-xr-xr-x 1 root root 37K Jan 12 08:55 /opt/xmltv/bin/tv_grab_zz_sdjson*
> ```
> 
> execs with error,
> 
> ```
> tv_grab_zz_sdjson --version
> 	Name "Params::Validate::NO_VALIDATION" used only once: possible typo at /opt/xmltv/bin/tv_grab_zz_sdjson line 238.
> 	XMLTV module version 0.5.70
> 	Invalid version $Id$ at /opt/xmltv/bin/tv_grab_zz_sdjson line 129.
> ```
> 
> checking
> 
> ```
> /opt/xmltv/bin/tv_grab_zz_sdjson
> 		#!/usr/bin/perl -w
> 		
> 3		my $grabber_cvs_id = '$Id$';
> 		...
> 129		my ($opt, $conf) = ParseOptions({
> 		    grabber_name => $grabber_name,
> 		    version => $grabber_cvs_id,
> 		...
> ```
> 
> I understand there's no 'next release' yet. But is it currently fixed in git src?

This is now resolved in git. Grabbers without an independently-managed version string will default to that of the core XMLTV library.

> It's unclear from reading above -- where/how does "Id" need to be set for the entire build-from-git-not-cvs to be 'happy'?

When CVS was used for source management, the "$Id$" CVS variable in each source file was automatically updated when checking out code to the current version of the file. These tags have now been removed, and calling --version for any grabber/utility should now provide a sane version number.
