### ISSUE TITLE
tv_grab_fr --slow : Can't call method "look_down" on an undefined value

### ISSUE THREAD

**Issue by melall** [XMLTV/xmltv#187]
XMLTV Version?
--------------
1.1.2

XMLTV Component?
----------------
tv_grab_fr

Perl Version
------------
perl 5, version 18, subversion 4 (v5.18.4)

Operating System
----------------
MacOS 10.14.6 (Mojave)

What happened?
--------------
$ tv_grab_fr --days 1 --slow --output ~/.xmltv/fr-tv-listings-slow.xml
Getting listings...: Can't call method "look_down" on an undefined value at /opt/local/bin/tv_grab_fr line 637.

What did you expect to happen?
------------------------------
no error.

Did you see any warnings/errors?
--------------------------------
Can't call method "look_down" on an undefined value at /opt/local/bin/tv_grab_fr line 637

What steps are needed to reproduce this issue?
----------------------------------------------
```
$ tv_grab_fr --configure
# choose bouquet = 5/Free, select all channels, or a few of them
$ tv_grab_fr --days 1 --slow
```
Please attach your config file below:
-------------------------------------
[tv_grab_fr.conf.txt](https://github.com/XMLTV/xmltv/files/9437699/tv_grab_fr.conf.txt)

Any other information?
----------------------
Work perfectly without --slow.
If I look to the end of the generated file I have:

 ```
 <channel id="tv5mondefbs.telestar.fr">
    <display-name lang="fr">TV5 MONDE FBS</display-name>
```
Which is the last channel in my configuration. This suggest we cannot grab the first program.
With another configuration with all channels I get the same error.
I removed the cache folder, tried again and got the same problem.

**Comment by honir** [comment]
This is due to an error on the source website TéléStar. Some of their own links point to pages which return a "missing page" error (code 404 or 410).

See for example: National Geographic channel for tonight. Clicking on "Air crash" S0E2 (21:50) gives a detail page. But clicking on "Air crash" S11E3 (22:40) returns a page-not-found error.

Perhaps you might like to report these "broken links" to TéléStar?

I've fixed tv_grab_fr (on github) so that it runs to completion, but note that data will be missing for any TV programmes which return 404/410

Please give it a try and let me know if it fixes your issue.

**Comment by melall** [comment]
Hello,

Thank you for the fix. It took some time for me to update just this resource in my macports installation, but now it run upon completion successfully.

I didn't check the results yet, I may report missing links to telestatrafterwards.

Best regards,
-- 
Maurice.
