### ISSUE TITLE
tv_grab_uk_tvguide --configuration, No Channels or Cache returned.

### ISSUE THREAD

**Issue by UtopiaOpera** [XMLTV/xmltv#188]
Thanks for taking the time to report an issue. Please take a moment to review our open/closed issues above, in case your issue has already been reported.

If you are reporting a new issue, please give your issue a descriptive title and fill out the blanks below, providing as much information as possible.

XMLTV Version?
--------------
1.0.0-1

XMLTV Component?
----------------
tv_grab_uk_tvguide

Perl Version
------------
v5.32.1

Operating System
----------------
Debian GNU/Linux 11 (bullseye) aarch64

What happened?
--------------
No channel data seemingly returns

What did you expect to happen?
------------------------------
The configurator to offer me channels to select

Did you see any warnings/errors?
--------------------------------
No

What steps are needed to reproduce this issue?
----------------------------------------------
tv_grab_uk_tvguide --configuration

Please attach your config file below:
-------------------------------------
cachedir=/home/pi/.xmltv/cache

Any other information?
----------------------
It gets to "Select channels" and then exits.
Cache location has nothing in it.

Here is the output from running --configuration.

```
$ tv_grab_uk_tvguide --configure
tv_grab_uk_tvguide uses a cache with files that it has already downloaded. Please specify where the cache shall be stored.
Directory to store the cache in: [/home/pi/.xmltv/cache]
Parsing result: (nothing to do)====================================================]
Reformatting: 100% [=========================================================]
Select the channels that you want to receive data for.
```

**Comment by honir** [comment]
tv_grab_uk_tvguide in version 1.0.0 is now broken.

Please upgrade to XMLTV 1.1.2

**Comment by UtopiaOpera** [comment]
Searching apt, that's the only version list, and listed as stable:

```
apt list -a xmltv

Listing... Done
xmltv/stable,stable,now 1.0.0-1 all [installed]
```

**Comment by honir** [comment]
The TVGuide website changed since version 1.0.0 of XMLTV and broke the grabber script. Version 1.1.2 works perfectly.

Unfortunately, the Debian 11 package manager doesn't support 1.1.2 (see [readme](https://github.com/XMLTV/xmltv#readme)). Debian 12 does, but that's probably no help to you. 

We have no control over that. You would need to ask the Debian package maintainers to try to get Debian 11 updated.

Alternatively -- and I don't know if it's possible with your software setup -- but you may be able to find and replace just the  `tv_grab_uk_tvguide` script with the [latest version](https://github.com/XMLTV/xmltv/tree/master/grab/uk_tvguide/tv_grab_uk_tvguide) from this git repo. That might work for you if there are no dependency issues.

**Comment by honir** [comment]
Closed as it's not an XMLTV issue.
