### ISSUE TITLE
is it normal speed?

### ISSUE THREAD

**Issue by ovladuk** [XMLTV/xmltv#207]
im using version 1.2.1 on windows 10 and i was just wondering if it's normal for it to be slow? I'm grabbing uk listings and it's been running for about an hour and it's only at 3%. is that normal?

**Comment by honir** [comment]
That's to be expected if you are fetching lots of channels and many days worth of listings. We follow best practice when it comes to grabbing this data, so it may appear "slow" but that is deliberate.

You didn't fill the form in so I don't know what you are attempting to fetch, but as a general rule you should only fetch data for the channels you actually watch (rather than all possible channels). 

Similarly don't try and fetch 14 days' worth of listings every day - there's no need. Listings beyond 3 days hence rarely change until the last minute. Fetching everything just wastes your time. For example, I fetch days 1-3 + day 8. This gives me an up-to-date schedule for the next 3 days and adds one new day onto the end. Fetching the days in between would not change anything.
