### ISSUE TITLE
tv_grab_zz_sdjson_sqlite needs --manage-lineups in summary

### ISSUE THREAD

**Issue by rmeden** [XMLTV/xmltv#38]
When you execute tv_grab_zz_sdjson_sqlite without any parameters it displays a list of options. --manage-lineups is missing.

**Comment by rmeden** [comment]
oops.. should have checked current repository. :(

**Comment by garybuhrmaster** [comment]
Some of this is an artifact of using the project libraries and using extra_options with ParseOptions.  If you run the command with --info the entire pod is provided, which includes a reference to --manage-lineups.  If you run with --help the project provided ParseOptions routine provides the output and only displays the standard xmltv compliant options, not showing the extra_options that were specified to ParseOptions, such as --manage-lineups (and some others for this grabber).  The grabber could replace/override ParseOptions, but since --info was able to be more complete as to even why you want to use any of the extra_options, including --manage-lineups, such work has never managed to get any real traction on my part.  Alternatively, the grabber could potentially move at least some of the --manage-lineup functionality into a much longer set of configure steps (although I think in practice trying to continue to support the --configure-api functionality with the capability of managing lineups upstream might be overly complex), but the remaining extra_options would still need to be dealt with by ParseOptions for --help to be actually complete.

A bit of historical perspective might be useful.  A long time ago during the initial development of the grabber that became known as tv_grab_zz_sdjson_sqlite there was hope on my part that eventually much of what --manage-lineups performs would not be necessary in the longer term because the upstream guide provider would offer as at least an option their own program or (perhaps web based) service to configure the subscribed lineups for the json side of the house just like they do with the legacy DataDirect compliant service.  Obviously that never happened, and then --manage-lineups was expanded to perform some other functionality (if you have a hammer...).  If the upstream guide provider did start to offer the lineup management functions, removing/changing the remain parts of --manage-lineups in the grabber would be a smaller effort.  But there is still ParseOptions and the lack of extra_options help text.  The challenge is how to make something that is done as a new users first experience (configuration) easy to understand and perform, even if it is done (typically) only once or twice for their application (and if they do it again in two years, they will likely have forgotten any arcane knowledge they learned the first time anyway).  tv_grab_zz_sdjson_sqlite --info does include a section on initial installation in an attempt to be helpful, but perhaps there needs to be better documentation elsewhere not only for that grabber, but others.  The wiki seems a bit sparse for a new user.

**Comment by garybuhrmaster** [comment]
> Hey Gary.. I closed the giithub ticket about --manage-lineups... I thought I saw it added to the code, but XMLTV.EXE still doesn't show it in --HELP after an update. 

Correct.  As stated, this is a bug in the ParseOptions xmltv library code.  If you want to fix the library code to show the specified extra_options, or allow grabbers to provide different help, I think that would be overall goodness.  Or perhaps document that ParseOptions is dead, and remove it, and require any/all grabbers currently using it to provide their own options parser.

> The in-app management of lineups is considered a feature. :) 

For at least some cases, having the option to do things in-app is probably goodness.  I like options (as long as they are parsed correctly by the library code :).  I think in the case of Schedules Direct that people can currently configure via the web page for the legacy DD service, but then it does not update their JSON lineups has been shown to confuse a different set of people.
