### ISSUE TITLE
tv_grab_pt_vodafone: upstream site changes

### ISSUE THREAD

**Issue by knowledgejunkie** [XMLTV/xmltv#72]
XMLTV Version?
--------------

Latest git

XMLTV Component?
----------------

tv_grab_pt_vodafone

What happened?
--------------

Failure to retrieve channels/listings.

What did you expect to happen?
------------------------------

Normal listings retrieval during testing.

Did you see any warnings/errors?
--------------------------------
(Please paste any warnings/errors, if available)

$ less t_pt_vodafone_1.log
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://tvnetvoz.vodafone.pt/?action=getPrograms">here</a>.</p>
</body></html>

What steps are needed to reproduce this issue?
----------------------------------------------

Run/test the grabber

**Comment by higuita** [comment]
yep, Vodafone PT switched from the web based tv-guide/silverlight based stream to a new app that only work on android/iphone and windows/mac. Already requested linux support, but unknown if we will get it.

I sniffed the apps calls and build a quick script to grab the info again from the new endpoint... but it requires iterate every channel and every program, so its lot slower than the older web-based info.

I'm trying to find if there a better way to get all the info directly instead of getting everything one by one and will report back

**Comment by knowledgejunkie** [comment]
@higuita  Thank you for the update!

**Comment by higuita** [comment]
I have already working a shell script with the new EPG endpoints and already ask nsenica to port it to perl when he have some free time :)

But while it is not ported, some people may the shell version useful as a temporary workaround: https://github.com/higuita/vodafone.pt-xmltv/blob/master/shell/tv_grab_pt_vdf3.sh
